[wip] Extending the Symbol Table
[日記]
- Symbol Table の outer 周りでどハマりしている
- ダメだったパターンを記録するシリーズ第三弾
  - これでいけると思っていたんだけど...
- Rc/RefCell をやめて、typed_arena を導入
  - SymbolTable#outer が結局 LinkedList なので、typed_arena に入れて生存期間問題を隠蔽する
  - ここ自体はうまくいった
- が、enter_scope() のところでダメ
  - self.symbol_table の付け替えのところでライフタイムがコンフリクトする

  ```
  error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'a` due to conflicting requirements
     --> src/compiler/mod.rs:148:14
      |
  148 |             .new_enclosed_symbol_table(self.symbol_table);
      |              ^^^^^^^^^^^^^^^^^^^^^^^^^
      |
  note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 139:5...
     --> src/compiler/mod.rs:139:5
      |
  139 | /     pub fn enter_scope(&mut self) {
  140 | |         let scope = CompilationScope {
  141 | |             instructions: Instructions(vec![]),
  142 | |             last_instruction: None,
  ...   |
  148 | |             .new_enclosed_symbol_table(self.symbol_table);
  149 | |     }
      | |_____^
  note: ...so that reference does not outlive borrowed content
     --> src/compiler/mod.rs:148:40
      |
  148 |             .new_enclosed_symbol_table(self.symbol_table);
      |                                        ^^^^^^^^^^^^^^^^^
  note: but, the lifetime must be valid for the lifetime `'a` as defined on the impl at 35:6...
     --> src/compiler/mod.rs:35:6
      |
  35  | impl<'a> Compiler<'a> {
      |      ^^
  note: ...so that the types are compatible
     --> src/compiler/mod.rs:148:14
      |
  148 |             .new_enclosed_symbol_table(self.symbol_table);
      |              ^^^^^^^^^^^^^^^^^^^^^^^^^
      = note: expected  `&compiler::symbol_table::SymbolTableArena<'_>`
                 found  `&compiler::symbol_table::SymbolTableArena<'a>`
  ```

- 厳しい...
  - ここだけで2ヶ月かかっているぞ...!
- そもそもから考え直す
  - outer 使ってリストっぽくしているけど、実際には enter_scope でスタックが積まれて resolve の時に前のも探索するだけでは
  - self.symbol_table として現在を持ってるけど、スタックの最上位のが現在なのでは
- というわけでこの方向は捨てる...